### ISSUE TITLE
Add "course id" field to the report

### ISSUE THREAD

**Issue by ravellom** [vadimonus/moodle-report_extendedlog#4]
Hello
Congratulations and thank you for this wonderful plugin.
It has been very useful for me to provide information to the application that I am developing: https://moodle-py.herokuapp.com (in Spanish for now)
There is only something that would be helpful to add, the course id, since there are global analyzes that I need the course id to make analysis and comparisons, for example, courses within a category.
Thank you in advance for your help.

**Comment by vadimonus** [comment]
It's not trivial improvement - this report uses standard report table, same as other log reports. But you can allways create merge request, to show, how you see it.

On the other hand, you should not use this plugin for automated data collection - it's intended to be used by human. For automatization you should create your own local plugin, build api methods, and use them for your app.

**Comment by ravellom** [comment]
Hello
You are right, what I thought from your answer and it has made me affirm that if I want this version of my app to use the standard report it should not depend on other fields that it does not provide, I have found another solution.
For the next version of the app, a rest API with these specificities and others will be implemented.
Thanks for your reply
