### ISSUE TITLE
Moodle 4 support

### ISSUE THREAD

**Issue by acquaalta** [vadimonus/moodle-report_extendedlog#6]
Hi,
Could you please add support for Moodle 4?
Even if the current version of the plugin would work on Moodle 4, an official support would be great.

Thanks even for considering it :-)

**Comment by vadimonus** [comment]
Sorry, i had no time to check if this plugin is fully compatible with 4.0. If you can confirm, that plugin works as expected with both default and classic themes, i can mark this version as supported.

Next time you may ask such questions as comment in moodle plugins directory, without creating issue on github.

**Comment by acquaalta** [comment]
Hi,
I did a basic sanity test of the plugin on Moodle 4.0.2, when using both themes (Boost and Classic), and the plugins seems to work. Please note that I didn't do an extensive test of the plugin and didn't try all its options.

Regarding the comment/issue thing, OK. In the past I usually saw developers that wrote that opposite (to please open an issue and not a comment on the plugin page).

Thanks

**Comment by vadimonus** [comment]
Tested on latest master, seems working ok, marked as supported up to 4.3
